-- 001_initial_schema.sql
-- Migration: Create ExpenseSplitter schema for Supabase (PostgreSQL)
-- Run this in the Supabase SQL Editor to set up the database.

-- 1. Users: the core identity table
-- All IDs are TEXT (generated by idService.js, e.g. "u1716298123456x7k9q2m")
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    avatar TEXT NOT NULL DEFAULT '👤',
    email TEXT
);

-- 2. Accounts: authentication credentials (one per user)
CREATE TABLE IF NOT EXISTS accounts (
    id BIGSERIAL PRIMARY KEY,
    user_id TEXT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    salt TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_accounts_email ON accounts(email);

-- 3. App state: single-row table for currentUserId
CREATE TABLE IF NOT EXISTS app_state (
    id INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    current_user_id TEXT NOT NULL REFERENCES users(id)
);

-- app_state row is inserted by the seed/initialization process, not here

-- 4. Groups: expense-sharing groups
-- "groups" is a SQL reserved word, so the physical table is "groups_table"
CREATE TABLE IF NOT EXISTS groups_table (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    emoji TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- 5. Group members: many-to-many junction
CREATE TABLE IF NOT EXISTS group_members (
    group_id TEXT NOT NULL REFERENCES groups_table(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_group_members_user_id ON group_members(user_id);

-- 6. Expenses: individual expenses within groups
CREATE TABLE IF NOT EXISTS expenses (
    id TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    amount NUMERIC(10,2) NOT NULL CHECK (amount > 0),
    paid_by TEXT NOT NULL REFERENCES users(id),
    category TEXT NOT NULL,
    date TEXT NOT NULL,
    group_id TEXT NOT NULL REFERENCES groups_table(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_expenses_group_id ON expenses(group_id);

-- 7. Expense split members: who shares each expense
CREATE TABLE IF NOT EXISTS expense_split_members (
    expense_id TEXT NOT NULL REFERENCES expenses(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (expense_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_expense_split_members_expense_id ON expense_split_members(expense_id);

-- ============================================================================
-- Stored procedure: sync_full_database
-- Called by supabaseService.writeDb() via supabase.rpc()
-- Receives the full in-memory DB as JSONB and performs an atomic delete+re-insert
-- within a single transaction (all-or-nothing).
-- ============================================================================
CREATE OR REPLACE FUNCTION sync_full_database(
    p_current_user_id TEXT,
    p_users JSONB,
    p_accounts JSONB,
    p_groups JSONB
) RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    group_record RECORD;
    expense_record RECORD;
BEGIN
    -- Phase 1: Clear all existing data (children first, then parents)
    -- WHERE true is required by Supabase's safety guard against unfiltered deletes
    DELETE FROM expense_split_members WHERE true;
    DELETE FROM expenses WHERE true;
    DELETE FROM group_members WHERE true;
    DELETE FROM groups_table WHERE true;
    DELETE FROM accounts WHERE true;
    DELETE FROM app_state WHERE true;
    DELETE FROM users WHERE true;

    -- Phase 2: Insert users
    INSERT INTO users (id, name, avatar, email)
    SELECT
        x.id,
        x.name,
        COALESCE(x.avatar, '👤'),
        x.email
    FROM jsonb_to_recordset(p_users) AS x(
        id TEXT, name TEXT, avatar TEXT, email TEXT
    );

    -- Phase 3: Insert app state
    INSERT INTO app_state (id, current_user_id) VALUES (1, p_current_user_id);

    -- Phase 4: Insert accounts (if any)
    -- In-memory field names are camelCase, table columns are snake_case
    IF p_accounts IS NOT NULL AND jsonb_array_length(p_accounts) > 0 THEN
        INSERT INTO accounts (user_id, email, password_hash, salt, created_at)
        SELECT
            x."userId",
            x.email,
            x."passwordHash",
            x.salt,
            x."createdAt"
        FROM jsonb_to_recordset(p_accounts) AS x(
            "userId" TEXT, email TEXT, "passwordHash" TEXT, salt TEXT, "createdAt" TEXT
        );
    END IF;

    -- Phase 5: Insert groups + members + expenses + splits
    IF p_groups IS NOT NULL AND jsonb_array_length(p_groups) > 0 THEN
        -- Insert groups first (in-memory uses camelCase: createdAt)
        INSERT INTO groups_table (id, name, emoji, created_at)
        SELECT
            x.id,
            x.name,
            x.emoji,
            x."createdAt"
        FROM jsonb_to_recordset(p_groups) AS x(
            id TEXT, name TEXT, emoji TEXT, "createdAt" TEXT
        );

        -- Iterate through each group to insert members, expenses, and splits
        FOR group_record IN
            SELECT * FROM jsonb_to_recordset(p_groups) AS x(
                id TEXT, members JSONB, expenses JSONB
            )
        LOOP
            -- Insert group_members (members are full user objects with id field)
            IF group_record.members IS NOT NULL AND jsonb_array_length(group_record.members) > 0 THEN
                INSERT INTO group_members (group_id, user_id)
                SELECT group_record.id, member_data->>'id'
                FROM jsonb_array_elements(group_record.members) AS member_data;
            END IF;

            -- Insert expenses and their split members
            IF group_record.expenses IS NOT NULL AND jsonb_array_length(group_record.expenses) > 0 THEN
                -- First, insert expenses
                INSERT INTO expenses (id, description, amount, paid_by, category, date, group_id)
                SELECT
                    e_data->>'id',
                    e_data->>'description',
                    (e_data->>'amount')::NUMERIC,
                    e_data->>'paidBy',
                    e_data->>'category',
                    e_data->>'date',
                    group_record.id
                FROM jsonb_array_elements(group_record.expenses) AS e_data;

                -- Then, insert split members for each expense
                FOR expense_record IN
                    SELECT
                        e_data->>'id' AS exp_id,
                        e_data->'splitBetween' AS split_data
                    FROM jsonb_array_elements(group_record.expenses) AS e_data
                LOOP
                    IF expense_record.split_data IS NOT NULL AND
                       jsonb_array_length(expense_record.split_data) > 0 THEN
                        INSERT INTO expense_split_members (expense_id, user_id)
                        SELECT
                            expense_record.exp_id,
                            split_user_id
                        FROM jsonb_array_elements_text(expense_record.split_data) AS split_user_id;
                    END IF;
                END LOOP;
            END IF;
        END LOOP;
    END IF;
END;
$$;
